NA = "не указано"
GROUPS = {
    "даты эпизода": ["admission_date", "discharge_date"],
    "диагноз": [
        "art_hyper",
        "atr_fibril",
        "ckd",
        "copd",
        "diagnosis_icd",
        "dm",
        "hf",
        "killip",
        "mi_localisation",
        "tlt",
        "type_acs",
    ],
    "осмотр при поступлении": ["bmi", "bp", "bpm", "height", "rr", "smoking", "spo2", "weight"],
    "ЭКГ": ["ecg_avb", "ecg_bpm", "ecg_elevation", "ecg_rythm"],
    "ЭХО-КГ": ["echo_ef", "echo_lvd", "echo_lvd_2", "echo_mr", "echo_zone"],
    "рентген грудной полости": ["rg_date", "rg_pc"],
    "коронарография": ["ca_date", "ca_fact", "ca_lad", "rca"],
    "Лабораторные данные": [
        "card_trop",
        "crea",
        "glu",
        "hb",
        "ldl",
        "leucocytes",
        "thrombocytes",
        "tot_chol",
    ],
    "медикаментозная терапия": [
        "2_aag",
        "ace_ing_sartan",
        "anticoagulant",
        "aspirin",
        "bb",
        "statin",
    ],
}
KEYS = [k for g in GROUPS.values() for k in g]
assert len(KEYS) == 50
RANGES = {
    "height": (100, 230),
    "weight": (20, 300),
    "bmi": (10, 70),
    "bpm": (20, 250),
    "rr": (5, 60),
    "spo2": (40, 100),
    "ecg_bpm": (20, 250),
    "echo_ef": (10, 90),
    "echo_lvd": (2.5, 95),
    "echo_lvd_2": (2.0, 80),
    "crea": (10, 3000),
    "glu": (0.5, 80),
    "hb": (30, 250),
    "ldl": (0.1, 15),
    "leucocytes": (0.2, 150),
    "thrombocytes": (5, 1500),
    "tot_chol": (1, 25),
}
